CREATE SEQUENCE bl_3nf.sales
INCREMENT BY 1
    START WITH 1
    MINVALUE 0
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE bl_3nf.products
INCREMENT BY 1
    START WITH 1
    MINVALUE 0
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE bl_3nf.employees
INCREMENT BY 1
    START WITH 1
    MINVALUE 0
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE bl_3nf.sequence_common_1
INCREMENT BY 1
    START WITH 1
    MINVALUE 0
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE bl_3nf.sequence_common_2
INCREMENT BY 1
    START WITH 1
    MINVALUE 0
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE bl_3nf.customers
INCREMENT BY 1
    START WITH 1
    MINVALUE 0
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE bl_3nf.stores
INCREMENT BY 1
    START WITH 1
    MINVALUE 0
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
    