CREATE SEQUENCE sequence_stores
	AS BIGINT
	INCREMENT BY 1
    START WITH 1
    MINVALUE 0;
    
CREATE SEQUENCE sequence_products
	AS BIGINT
	INCREMENT BY 1
    START WITH 1
    MINVALUE 0
    
CREATE SEQUENCE sequence_employees
	AS BIGINT
	INCREMENT BY 1
    START WITH 1
    MINVALUE 0;

CREATE SEQUENCE sequence_payment_types
	AS BIGINT
	START WITH 1
    MINVALUE 0
    INCREMENT BY 1;
    
CREATE SEQUENCE sequence_coupons
	AS BIGINT
	START WITH 1
    MINVALUE 0
    INCREMENT BY 1;

CREATE SEQUENCE sequence_customers
	AS BIGINT
	START WITH 1
    MINVALUE 0
    INCREMENT BY 1;

CREATE SEQUENCE sequence_sales
	AS BIGINT
	START WITH 1
    MINVALUE 0
    INCREMENT BY 1;


	
